#!/bin/bash

mkdir /opt/clash && cd /opt/clash
wget https://dl3.ssrss.club/clash-linux-amd64-v1.9.0.gz  
wget -O /opt/clash/config.yaml "https://new.ssrss.de/sub?target=clash&new_name=true&url=https%3A%2F%2Fssrss.de%2Fs%2FSHAQZNNQGKRR&udp=true&tfo=true&config=https%3A//ssrss.de/ssrss.ini"
wget https://dl3.ssrss.club/Country.mmdb
gunzip -c *.gz > clash && chmod +x clash

cat > /usr/lib/systemd/system/clash.service <<'EOF'
[Unit]
Description=clash
[Service]
TimeoutStartSec=0
ExecStart=/opt/clash/clash -d /opt/clash
[Install]
WantedBy=multi-user.target
EOF

systemctl enable clash
systemctl start clash
